### ISSUE TITLE
cannot find 'ApolloSchemaDownloadConfiguration'

### ISSUE THREAD

**Issue by morgz** [apollographql/iOSCodegenTemplate#11]
I believe I have followed all the setup instruction correctly. I am getting the following error when running:

`xcrun -sdk macosx swift run ApolloCodegen generate`

`ApolloCodegen/Sources/ApolloCodegen/main.swift:40:41: error: cannot find 'ApolloSchemaDownloadConfiguration' in scope
            let schemaDownloadOptions = ApolloSchemaDownloadConfiguration(using: .introspection(endpointURL: endpoint),`

&&

`ApolloCodegen/Sources/ApolloCodegen/main.swift:44:40: error: type 'ApolloSchemaDownloader' has no member 'fetch'
            try ApolloSchemaDownloader.fetch(with: schemaDownloadOptions)`

Using the latest version and swift 5.5 on an M1 Mac

**Comment by designatednerd** [comment]
Can you confirm what version of the Apollo library you have in your `Package.swift`? That type got renamed with `0.49.0` so if it's anything before that, that's probably why it's not finding it.

**Comment by morgz** [comment]
OK, I was using 0.42.0 of Apollo. Thanks
