### ISSUE TITLE
Make this a SPM package

### ISSUE THREAD

**Issue by pappalar** [apollographql/iOSCodegenTemplate#14]
Hello..

I don't want to manually install and update this CodeGen tool and keep the version of Apollo in sync by hand.
Why is this not directly a SPM package (in Apollo ios maybe..) 

or at least provide a way to download it as a SPM Package and use a config file?

**Comment by calvincestari** [comment]
Hi @racer1988, it's a reasonable suggestion.

Something that should make this stuff easier to use soon is that we will be building a CLI tool as part of the 1.0 alpha releases. The intent is for that to be available via Homebrew and you execute it along with a configuration file for code generation. Keep watching the 1.0 alpha releases to know when that is released.

**Comment by yehe01** [comment]
Has the team taken a look at this?
https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md
There are examples of integrating SwiftGen provided. I haven't tried but it looks very promising.

**Comment by calvincestari** [comment]
@yehe01 - yup, we're pretty excited about the possibilities that proposal could unlock! We won't be able to adopt anything until it's actually out in production though.

**Comment by pchmelar** [comment]
SwiftGen recently released support for SPM Plugins - https://github.com/SwiftGen/SwiftGen/issues/913
Support for other major iOS build tools is coming soon (https://github.com/krzysztofzablocki/Sourcery/issues/1023, https://github.com/realm/SwiftLint/issues/3840, etc)
It would be awesome to have this in Apollo as well. 🙂
What's your estimation / roadmap on this? 👀

**Comment by calvincestari** [comment]
Soon. We're planning for it to be part of the upcoming 1.0 release.

**Comment by calvincestari** [comment]
Posting an update on this issue that the [apollo-ios `release/1.0`](https://github.com/apollographql/apollo-ios/tree/release/1.0) branch [now supports SwiftPM plugins](https://github.com/apollographql/apollo-ios/blob/release/1.0/Package.swift#L23).

**This repo is very likely going to be archived as we near 1.0 GA with the content moving into the apollo-ios documentation where it's more discoverable to a wider audience.**
