### ISSUE TITLE
Compiling for iOS 11.0, but module 'ApolloCodegenLib' has a minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by axiel7** [apollographql/iOSCodegenTemplate#20]
I'm trying to the latest Apollo 1.0.0-beta.1 version, I downloaded the Codegen template from the [1.0.0-alpha](https://github.com/apollographql/iOSCodegenTemplate/tree/1.0.0-alpha) branch. But when I try to build the project, it gives this error on the `import ApolloCodegenLib` line:

`Compiling for iOS 11.0, but module 'ApolloCodegenLib' has a minimum deployment target of iOS 12.0`

**Comment by calvincestari** [comment]
Apollo code generation is not meant to build and run on iOS, it's not designed for that platform.

If you take a look in the [Package.swift for iOSCodegenTemplate](https://github.com/apollographql/iOSCodegenTemplate/blob/1.0.0-alpha/ApolloCodegen/Package.swift#L8) you'll see it only supports the macOS platform. The apollo-ios package has many targets and as a result [supports a broader range of platforms](https://github.com/apollographql/apollo-ios/blob/release/1.0/Package.swift#L8) but there is still a hard-coded limitation of [ApolloCodegenLib ony supporting macOS](https://github.com/apollographql/apollo-ios/blob/release/1.0/Sources/ApolloCodegenLib/ApolloCodegen.swift#L6). If SPM supported platform-per-target we'd specify the limitation that way but I don't believe that's possible right now.

**Comment by axiel7** [comment]
Okay I feel stupid right now.
For anyone who has the same problem, please make sure the target destination is checked to a Mac platform.
By default my Xcode has checked iOS.

**Comment by calvincestari** [comment]
There's no stupid questions, happy to help. Let us know if you have any other issues, good luck with your project.

**Comment by Avijit-creator** [comment]
Hello @axiel7 , @calvincestari  I updated my xcode from 13.4 to 14.1. Suddenly I am getting this issue. How do I have to set target destination for ApolloCodegenLib to a Mac platform? It has been working fine with lower versions of xcode. Never got this issue.
Upgrading to Xcode 14.1 causing this problem.

**Comment by calvincestari** [comment]
@Avijit-creator I don't completely understand the issue you're getting. ApolloCodegenLib is macOS only; make sure the target that uses it can deploy to macOS only. Sharing the build error might help narrow down the problem.

**Comment by Avijit-creator** [comment]
@calvincestari I have been using this https://github.com/apollographql/apollo-ios.git in my iOS app. I am importing ApolloCodegenLib.

**Comment by axiel7** [comment]
@Avijit-creator just make sure you have selected a macOS target on the target selector
<img width="660" alt="Screenshot 2023-01-23 at 19 01 42" src="https://user-images.githubusercontent.com/12379835/214115299-e11fba3c-6364-4379-97f3-f041fc0b9868.png">

**Comment by Avijit-creator** [comment]
Hi @axiel7 , I am using like this. Where I can set the macOS on target selector? can you tell me the path. I am developing an ios app. Are you saying I have to set the the target for ApolloCodegenLib only? How can I do that. My project looks like this 
<img width="977" alt="Screenshot 2023-01-23 at 11 38 31 PM" src="https://user-images.githubusercontent.com/87003452/214116959-b5f5880e-e0c3-4de2-b172-a0fc758167d5.png">

**Comment by calvincestari** [comment]
This is also an unwanted side-effect of distributing [all our library products](https://github.com/apollographql/apollo-ios/blob/main/Package.swift#L14) in a single [`Package.swift`](https://github.com/apollographql/apollo-ios/blob/main/Package.swift) file; SPM doesn't yet support per-target platform definitions so we have the [root platform definition](https://github.com/apollographql/apollo-ios/blob/main/Package.swift#L8) which I think is leading to this confusing error.

Ideally we could specify that `ApolloCodegenLib` was for macOS only. We've discussed possibly splitting `ApolloCodegenLib` out into it's own package to avoid these kind of errors and have a more targeted product.

**Comment by calvincestari** [comment]
@Avijit-creator you shouldn't have `ApolloCodegenLib` as a dependency for any target that can deploy to iOS, it's not needed. Create a separate target/project if you need to.

**Comment by axiel7** [comment]
@Avijit-creator you don't need to change anything in your app project. Open the `Package.swift` file of `ApolloCodegenLib` in Xcode and then change the target to macOS

**Comment by axiel7** [comment]
@Avijit-creator you need to select it with the selector I highlighted in my previous screenshot

**Comment by Avijit-creator** [comment]
@axiel7 your suggestion compiles the Apollocodegen Library perfectly but my app is not compiling.

**Comment by axiel7** [comment]
> @axiel7 your suggestion compiles the Apollocodegen Library perfectly but my app is not compiling.

As mentioned by @calvincestari you don't need to add `ApolloCodegenLib` to your project. You only need to execute it and generate the necessary Apollo files

**Comment by Avijit-creator** [comment]
@calvincestari I have been so far downloading the schema with importing ApolloCodgenLib. I have been using this code to download schema from my custom server as 
try ApolloSchemaDownloader.fetch(with: schemaDownloadOptions)
Now the schema is not downloading. If we not use ApolloCodgenLib then how can I download schema from my server? If there is a tutorial link for that how to do it? Please share me the tutorial link. 

Thanks!

**Comment by calvincestari** [comment]
> @calvincestari I have been so far downloading the schema with importing ApolloCodgenLib. I have been using this code to download schema from my custom server as try ApolloSchemaDownloader.fetch(with: schemaDownloadOptions) Now the schema is not downloading.

You can still do this, as long as it is a macOS deployment target and none of your iOS deployed targets link to `ApolloCodegenLib`. Nothing should have changed to prevent you doing that.

The [Codegen CLI](https://www.apollographql.com/docs/ios/code-generation/downloading-schema#2-codegen-cli) also supports downloading a schema with the [`fetch-schema`](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#fetch-schema) command. You could try that or configure your Xcode projects so an iOS deployment target does not import `ApolloCodegenLib`.

**Comment by calvincestari** [comment]
> @axiel7 your suggestion compiles the Apollocodegen Library perfectly but my app is not compiling.

Remove `ApolloCodegenLib` from your list of linked frameworks on the iOS target, and do not import it into any swift file that can be deployed to iOS. Once you do that, I don't see any reason why it shouldn't build.

**Comment by Avijit-creator** [comment]
@calvincestari @axiel7 Thanks a lot for your support.
