### ISSUE TITLE
Template out of date with beta 4?

### ISSUE THREAD

**Issue by kylebrowning** [apollographql/iOSCodegenTemplate#22]

**Comment by calvincestari** [comment]
I've created a new branch [release/1.0](https://github.com/apollographql/iOSCodegenTemplate/tree/release/1.0) to follow the same naming convention as [apollo-ios](https://github.com/apollographql/apollo-ios/tree/release/1.0). That branch is also now compatible with apollo-ios `1.0.0-beta.4` code.

**This repo is very likely going to be archived as we near 1.0 GA with the content moving into the apollo-ios documentation where it's more discoverable to a wider audience.**
