### ISSUE TITLE
Add ApolloCLI/ to .gitignore

### ISSUE THREAD

**Issue by joel-perry** [apollographql/iOSCodegenTemplate#5]
Not adding the ApolloCLI folder to .gitignore causes this (very large) folder to get committed with your project. I have already added this to my own project, but think this should be added in the template, as well.

There may be a good reason not to do this, and, if so, please .gitignore this request.

**Comment by calvincestari** [comment]
Hi @joel-perry, I'd be happy to accept a PR if you've got the time.

**Comment by joel-perry** [comment]
@calvincestari Done
